print ('======== DESAFIO 01 ========')
print('Boas vindas ao System Arkan!')
nome = input('Para iniciar, insira seu nome: ')
sobrenome = input('E qual seu sobrenome? ')
dia = input('Muito prazer ' + nome + '. Em que dia você nasceu? ')
mes = input('Em qual mês? ')
ano = input('Para finalizar, ensira o ano do nascimento: ')
print ('Aguarde uns instantes ...')
print ('Seu cadastro foi concluido com sucesso!')
print ('Nome: ', nome, sobrenome + '. ' 'Data de nascimento: ' + dia + '/' + mes + '/' + ano)